name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies and generate docs
        run: |
            cd notifications
            npm ci
            npx @compodoc/compodoc -p tsconfig.json -d ../docs/notifications
            cd ../customer-app
            npm ci
            npx @compodoc/compodoc -p tsconfig.json -d ../docs/customer-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
